version: "3.7"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    networks:
      - valle-magico-network
    depends_on: 
      - db
    restart: always
    environment:
      - DB_HOST
      - DB_PORT
      - DB_USERNAME
      - DB_PASSWORD
      - DB_ONE_NAME
      - DB_TWO_NAME
      - DB_ROOT_PASSWORD
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: valle-magico-db
    volumes:
       - ./docker-db/script.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD:  "${DB_PASSWORD}"
    ports:
      - "3306:3306"
    networks:
      - valle-magico-network
networks:
  valle-magico-network:
    driver: bridge